services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # Puerto SMTP
      - "8025:8025"  # Interfaz Web UI

  backend:
    build: ./backend
    container_name: java_backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myappdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      BONITA_SERVER_URL: http://host.docker.internal:23253/bonita
      CLOUD_SERVICE_URL: http://host.docker.internal:8085/Dssd2025Cloud
      # Email Configuration - Usando MailHog para desarrollo/pruebas
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: noreply@proyect-planning.com
      MAIL_PASSWORD: ""
    ports:
      - "8081:8081"
    depends_on:
      - db
      - mailhog
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: angular_frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/angular.json:/app/angular.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
    depends_on:
      - backend

volumes:
  postgres_data:
